docx:
	gcc-15 -Wall -o docx_decrypt docx_decrypt.c
	./docx_decrypt

png:
	gcc-15 -Wall -o png_decrypt png_decrypt.c
	./png_decrypt

pdf:
	gcc-15 -Wall -o pdf_decrypt pdf_decrypt.c
	./pdf_decrypt

jpg:
	gcc-15 decrypt_jpg.c -o decrypt_jpg
	./decrypt_jpg ../test_encrypt/Drawing1.jpg ../decrypted/Drawing1.jpg


txt:
	gcc-15 decrypt_txt.c -o decrypt_txt
	./decrypt_txt ../test_encrypt/1.txt ../decrypted/1.txt
