docx:
	gcc-15 -Wall -o docx_decrypt docx_decrypt.c
	./docx_decrypt

png:
	gcc-15 -Wall -o png_decrypt png_decrypt.c
	./png_decrypt

pdf:
	gcc-15 -Wall -o pdf_decrypt pdf_decrypt.c
	./pdf_decrypt

jpg:
	gcc-15 -Wall -o jpg_decrypt jpg_decrypt.c
	./jpg_decrypt

txt:
	gcc-15 -Wall -o txt_decrypt txt_decrypt.c
	./txt_decrypt
